### ISSUE TITLE
Invalid Cast Exception

### ISSUE THREAD

**Issue by vsederburg** [agileobjects/AgileMapper#110]
Hi, I just discovered this repo and it looks like exactly what I need... but I seem to get:

AgileObjects.AgileMapper.MappingException: 'An exception occurred mapping SavedQueryDto -> SavedQueryDto with rule set CreateNew.'
InvalidCastException

I'm calling it as:
 var dto = Mapper.Map(QueryDto).ToANew<SavedQueryDto>();

But I've also tried:
var dto = new SavedQueryDto();
QueryDto.Map().Over(dto);

and 
var clone = Mapper.DeepClone(QueryDto);

Any ideas what I'm doing wrong?
Thank you!

This is the mapping plan it generates:

```
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// Map SavedQueryDto -> SavedQueryDto
// Rule Set: CreateNew
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

sqdToSqdData =>
{
    SavedQueryDto sourceSavedQueryDto;
    try
    {
        sourceSavedQueryDto = sqdToSqdData.Source;

        var savedQueryDto = new SavedQueryDto();
        savedQueryDto.QueryName = sourceSavedQueryDto.QueryName;
        savedQueryDto.IsDefault = sourceSavedQueryDto.IsDefault;

        if (sourceSavedQueryDto.QueryId.HasValue)
        {
            savedQueryDto.QueryId = sourceSavedQueryDto.QueryId;
        }

        savedQueryDto.WorkspaceTypeId = sourceSavedQueryDto.WorkspaceTypeId;
        savedQueryDto.IsUserDefined = sourceSavedQueryDto.IsUserDefined;
        savedQueryDto.QueryTypeId = sourceSavedQueryDto.QueryTypeId;
        savedQueryDto.IsDirty = sourceSavedQueryDto.IsDirty;

        if (sourceSavedQueryDto.OriginalPropertyValues != null)
        {
            savedQueryDto.OriginalPropertyValues =
            {
                IObjectMappingData<Dictionary<string, object>, Dictionary<string, object>> dsosToDsosData;
                try
                {
                    dsosToDsosData = MappingDataFactory.ForChild(
                        sourceSavedQueryDto.OriginalPropertyValues,
                        savedQueryDto.OriginalPropertyValues,
                        sqdToSqdData.EnumerableIndex,
                        \"OriginalPropertyValues\",
                        0,
                        sqdToSqdData);

                    var dictionary_String_Object = dsosToDsosData.Target ?? new Dictionary<string, object>(dsosToDsosData.Source.Comparer);
                    var i = 0;
                    var enumerator = dsosToDsosData.Source.GetEnumerator();
                    try
                    {
                        while (true)
                        {
                            if (!enumerator.MoveNext())
                            {
                                break;
                            }

                            var targetKey = enumerator.Current.Key;
                            if (enumerator.Current.Value == null)
                            {
                                continue;
                            }

                            dictionary_String_Object[targetKey] = dsosToDsosData.Map(enumerator.Current.Value, null, i);
                            ++i;
                        }
                    }
                    finally
                    {
                        enumerator.Dispose();
                    }

                    return dictionary_String_Object;
                }
                catch (Exception ex)
                {
                    throw MappingException.For(
                        \"CreateNew\",
                        \"SavedQueryDto.OriginalPropertyValues\",
                        \"SavedQueryDto.OriginalPropertyValues\",
                        ex);
                }
            }
        }
        else
        {
            savedQueryDto.OriginalPropertyValues = new Dictionary<string, object>();
        }

        savedQueryDto.IsLinkedToDatabase = sourceSavedQueryDto.IsLinkedToDatabase;
        // No way to populate Properties (readonly array)

        return savedQueryDto;
    }
    catch (Exception ex)
    {
        throw MappingException.For(
            \"CreateNew\",
            \"SavedQueryDto\",
            \"SavedQueryDto\",
            ex);
    }
}
```

**Comment by SteveWilkes** [comment]
Hi!

Looks like you're wanting to deep clone your `SavedQueryDto`, so I'd say `Mapper.DeepClone()` is what you're after :)

There's nothing obvious in the mapping plan which would cause the exception, which makes me suspect it's happening somewhere within in the `dsosToDsosData.Map(enumerator.Current.Value, null, i);` call, while mapping one of the `OriginalPropertyValues` entries.

Could you let me know what entries there are in that dictionary? Also the `SavedQueryDto` class definition could be helpful.

Cheers,

Steve

**Comment by vsederburg** [comment]
You're exactly right. It's the OriginalPropertyValues dictionary that breaks it.
It's a dictionary of whatever value the dto properties had to start with.

Here's the contents:

◢ | [0] | {[QueryName, References]} | System.Collections.Generic.KeyValuePair<string, object>
  | Key | "QueryName" | string
  | Value | "References" | object {string}
◢ | [1] | {[IsDefault, False]} | System.Collections.Generic.KeyValuePair<string, object>
  | Key | "IsDefault" | string
  | Value | false | object {bool}
◢ | [2] | {[QueryId, 155]} | System.Collections.Generic.KeyValuePair<string, object>
  | Key | "QueryId" | string
  | Value | 155 | object {int}
◢ | [3] | {[WorkspaceTypeId, 1]} | System.Collections.Generic.KeyValuePair<string, object>
  | Key | "WorkspaceTypeId" | string
  | Value | 1 | object {int}
◢ | [4] | {[IsUserDefined, True]} | System.Collections.Generic.KeyValuePair<string, object>
  | Key | "IsUserDefined" | string
  | Value | true | object {bool}
◢ | [5] | {[QueryTypeId, 2]} | System.Collections.Generic.KeyValuePair<string, object>
  | Key | "QueryTypeId" | string
  | Value | 2 | object {int}

**Comment by SteveWilkes** [comment]
Ok, great! I'll check it out. Thanks! :)

**Comment by SteveWilkes** [comment]
This is fixed in the current v1.1 preview, which is now [on NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper/1.1.0-preview) as a prerelease package.

Thanks for the bug report - let me know how you get on!

Cheers,

Steve

**Comment by vsederburg** [comment]
Brilliant, works perfectly! 
I removed the DoNotMap attribute and test-ran v1.0 to verify that the error still occurred. Then installed the prerelease and ran again -- no errors, and the clone did handle that dictionary's values correctly.

Thanks so much!

**Comment by SteveWilkes** [comment]
No worries! Thanks again for the feedback - do let me know of anything else you find :)

**Comment by eliashdezr** [comment]
@SteveWilkes can this preview version be published on NuGet? :)

**Comment by eliashdezr** [comment]
@SteveWilkes thanks!

I might found another issue. I'm trying to map a `Dictionary<string, object>`, but i'm getting this exception:
![image](https://user-images.githubusercontent.com/6153607/49892395-80480180-fe0e-11e8-83ec-de3e36c5482f.png)

You can reproduce it with this:
```c#
private static void Main(string[] args)
{
    var from = new From
    {
        Properties = new Dictionary<string, object>()
        {
            { "int", 1 },
            { "double", 1.0 },
            { "decimal", 1m },
            { "string", "hello" },
            { "bool", true }
        }
    };

    var map = Mapper.Map(from).ToANew<To>();
}
public class From
{
    public Dictionary<string, object> Properties { get; set; }
}

public class To
{
    public Dictionary<string, object> Properties { get; set; }
}
```

**Comment by SteveWilkes** [comment]
Thanks for letting me know - it was the decimal causing it! I've fixed it and uploaded a preview2 package [to NuGet](https://www.nuget.org/packages/AgileObjects.AgileMapper/1.1.0-preview2).

**Comment by SteveWilkes** [comment]
This is fixed as of [v1.1](https://www.nuget.org/packages/AgileObjects.AgileMapper).

Thanks! :)
